name: PR Assignment

on:
  pull_request:
    types: [opened, reopened, unassigned]

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .github/scripts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: .github/scripts/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.github/scripts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run reviewer assignment
        run: node assign_reviewers.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EVENT_TYPE: ${{ github.event.action }}
          USER_MAP_URL: ${{ secrets.USER_MAP_URL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
