name: PR Assignment

on:
  pull_request_target:
    types: [opened, reopened, unassigned]

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: .github/scripts/pr-assigner/package-lock.json

      - name: Install dependencies
        working-directory: .github/scripts/pr-assigner
        run: npm ci

      - name: Run reviewer assignment
        working-directory: .github/scripts/pr-assigner
        run: node assign_reviewers.js
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT instead of default GITHUB_TOKEN
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EVENT_TYPE: ${{ github.event.action }}
          USER_MAP_URL: ${{ secrets.USER_MAP_URL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
